stages:
  - build:frontend
  - build:backend_include_frontend

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - .m2/

build-frontend:
  stage: build:frontend
  image: node:12-alpine
  script:
    - npm run build
  artifacts:
    paths:
      - target/classes/static

build-backend-include-frontend:
  stage: build:backend_include_frontend
  dependencies:
    - build-frontend
  needs:
    - job: build-frontend
      artifacts: true
  image: maven:3.6-jdk-11-slim
  script:
    - ./mvnw package
  artifacts:
    paths:
      - target
