stages:
  - build

build-frontend:
  image: coexcz/node-alpine
  scripts:
    - git clone https://github.com/aborigines/angular-webpack-docker-nginx.git
    - npm run build
  artifacts:
    paths:
      - target/classes/static

build-backend-include-frontend:
  image: maven:3.6.3-jdk-11-slim
  scripts:
    - ./mvnw install
  dependencies: frontend-build-job
  artifacts:
    paths:
      - target
