stages:
  - test:frontend
  - build:frontend
  - build:backend_include_frontend

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - .m2/

test-frontend:
  stage: test:frontend
  image: coexcz/node-alpine # node:12-alpine with git
  when: manual
  script:
    - git clone https://github.com/aborigines/angular-webpack-docker-nginx.git angular-webpack-docker-nginx
    - cd angular-webpack-docker-nginx
    - npm install --no-package-lock
    - npm run test
  artifacts:
    paths:
      - angular-webpack-docker-nginx

build-frontend:
  stage: build:frontend
  dependencies:
    - test-frontend
  needs:
    - job: test-frontend
      artifacts: true
  image: coexcz/node-alpine # node:12-alpine with git
  script:
    - cd angular-webpack-docker-nginx
    - npm install --no-package-lock
    - npm run build
  artifacts:
    paths:
      - angular-webpack-docker-nginx/target/classes/static

build-backend-include-frontend:
  stage: build:backend_include_frontend
  dependencies:
    - build-frontend
  needs:
    - job: build-frontend
      artifacts: true
  image: maven:3.6-jdk-11-slim
  script:
    - mkdir -p target/classes/
    - cp -r angular-webpack-docker-nginx/target/classes/static target/classes/
    - ./mvnw package
  artifacts:
    paths:
      - target
